services:
  dev: &dev
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    image: keboola/storage-api-client
    volumes:
      - ./:/code

  # Alias for standalone repo workflow compatibility
  tests:
    <<: *dev

  dev-xdebug:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci-xdebug
    image: keboola/storage-api-client-xdebug
    volumes:
      - ./:/code
