version: '2'
services:
  tests: &base
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_SESSION_TOKEN
    image: keboola/storage-api-tests
    environment:
      - STORAGE_API_URL
      - STORAGE_API_TOKEN
      - STORAGE_API_LINKING_TOKEN
      - STORAGE_API_MAINTENANCE_URL
      - STORAGE_API_TOKEN_WITH_OTHER_ADMIN_IN_SAME_ORGANIZATION
      - STORAGE_API_TOKEN_WITH_OTHER_ADMIN_IN_OTHER_ORGANIZATION
      - REDSHIFT_HOSTNAME
      - REDSHIFT_USER
      - REDSHIFT_PASSWORD
  dev: &dev
    <<: *base
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build:
      context: docker/xdebug

networks:
  default:
    external:
      name: connection_api-tests
