version: '2'
services:
  tests: &base
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID=${DRIVER_DOWNLOADS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${DRIVER_DOWNLOADS_SECRET_ACCESS_KEY}
        - AWS_SESSION_TOKEN
    image: keboola/storage-api-tests
    environment:
      - STORAGE_API_URL
      - STORAGE_API_TOKEN
      - STORAGE_API_LINKING_TOKEN
      - STORAGE_API_GUEST_TOKEN
      - STORAGE_API_READ_ONLY_TOKEN
      - STORAGE_API_SHARE_TOKEN
      - STORAGE_API_DEFAULT_BRANCH_TOKEN
      - STORAGE_API_REVIEWER_TOKEN
      - STORAGE_API_SECOND_REVIEWER_TOKEN
      - STORAGE_API_DEVELOPER_TOKEN
      - STORAGE_API_MAINTENANCE_URL
      - STORAGE_API_TOKEN_ADMIN_2_IN_SAME_ORGANIZATION
      - STORAGE_API_TOKEN_ADMIN_3_IN_OTHER_ORGANIZATION
      - MANAGE_API_TOKEN_ADMIN
      - MANAGE_API_TOKEN_WITHOUT_SCOPE
      - MANAGE_API_TOKEN_WITH_CREATE_PROTECTED_DEFAULT_BRANCH_TOKEN
      - REDSHIFT_HOSTNAME
      - REDSHIFT_USER
      - REDSHIFT_PASSWORD
      - REDSHIFT_NODE_COUNT
      - SUITE_NAME
      - TRAVIS_BUILD_ID
      - BQ_KEY_FILE_FOR_EXTERNAL_BUCKET
      - BQ_DESTINATION_PROJECT_SERVICE_ACC_EMAIL
  dev: &dev
    <<: *base
    volumes:
      - ./:/code
      - tools-cache:/tmp/tools-cache

  dev-xdebug:
    <<: *dev
    build:
      context: docker/xdebug
    image: keboola/storage-api-tests-xdebug
    command: tail -f /dev/null

networks:
  default:
    external:
      name: connection_api-tests

volumes:
  tools-cache:
