version: '2'
services:
  tests:
    build: .
    image: keboola/storage-api-tests
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    working_dir: /code
    command: >
       sh -c '
       composer install
       && ./vendor/bin/phpunit
       '
    environment:
      - STORAGE_API_URL
      - STORAGE_API_TOKEN
      - STORAGE_API_LINKING_TOKEN
      - STORAGE_API_MAINTENANCE_URL
      - REDSHIFT_HOSTNAME
      - REDSHIFT_USER
      - REDSHIFT_PASSWORD
  odbc:
    build:
      context: .
      dockerfile: DockerfileOdbcDownload
    volumes:
        - .:/code
    working_dir: /code