services:
  dev:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci
    image: keboola/storage-api-client
    volumes:
      - ./:/code

  dev-xdebug:
    build:
      context: ../..
      dockerfile: Dockerfile
      target: package-ci-xdebug
    image: keboola/storage-api-client-xdebug
    volumes:
      - ./:/code
