version: '2'
services:
  tests: &base
    build:
      context: .
    image: keboola/storage-api-tests
    environment:
      - STORAGE_API_URL
      - STORAGE_API_TOKEN
      - STORAGE_API_LINKING_TOKEN
      - STORAGE_API_GUEST_TOKEN
      - STORAGE_API_READ_ONLY_TOKEN
      - STORAGE_API_SHARE_TOKEN
      - STORAGE_API_DEFAULT_BRANCH_TOKEN
      - STORAGE_API_REVIEWER_TOKEN
      - STORAGE_API_SECOND_REVIEWER_TOKEN
      - STORAGE_API_DEVELOPER_TOKEN
      - STORAGE_API_MAINTENANCE_URL
      - STORAGE_API_TOKEN_ADMIN_2_IN_SAME_ORGANIZATION
      - STORAGE_API_TOKEN_ADMIN_3_IN_OTHER_ORGANIZATION
      - MANAGE_API_TOKEN_ADMIN
      - MANAGE_API_TOKEN_WITHOUT_SCOPE
      - MANAGE_API_TOKEN_WITH_CREATE_PROTECTED_DEFAULT_BRANCH_TOKEN
      - REDSHIFT_HOSTNAME
      - REDSHIFT_USER
      - REDSHIFT_PASSWORD
      - REDSHIFT_NODE_COUNT
      - SUITE_NAME
      - TRAVIS_BUILD_ID
      - BQ_KEY_FILE_FOR_EXTERNAL_BUCKET
      - BQ_DESTINATION_PROJECT_SERVICE_ACC_EMAIL
      - BQ_EXTERNAL_TABLE_GCS_BUCKET
      - BQ_EXTERNAL_BUCKET_REGION
      - SNOWFLAKE_HOST
      - SNOWFLAKE_USER
      - SNOWFLAKE_PASSWORD
      - SNOWFLAKE_DB_PREFIX
      - SNOWFLAKE_INBOUND_DATABASE_NAME
      - SNOWFLAKE_PRODUCER_HOST
      - SNOWFLAKE_PRODUCER_USER
      - SNOWFLAKE_PRODUCER_PASSWORD
      - SNOWFLAKE_PRODUCER_WAREHOUSE
      - SNOWFLAKE_PRODUCER_SHARED_DATABASE
      - SNOWFLAKE_PRODUCER_SHARE_NAME
  dev: &dev
    <<: *base
    volumes:
      - ./:/code
      - tools-cache:/tmp/tools-cache

  dev-xdebug:
    <<: *dev
    build:
      context: docker/xdebug
    image: keboola/storage-api-tests-xdebug
    command: tail -f /dev/null

networks:
  default:
    external:
      name: connection_api-tests

volumes:
  tools-cache:
