version: '2'
services:
  tests: &base
    build:
      context: .
      args:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
    image: keboola/storage-api-tests
    environment:
      - STORAGE_API_URL
      - STORAGE_API_TOKEN
      - STORAGE_API_LINKING_TOKEN
      - STORAGE_API_MAINTENANCE_URL
      - REDSHIFT_HOSTNAME
      - REDSHIFT_USER
      - REDSHIFT_PASSWORD
  dev:
    <<: *base
    volumes:
      - ./:/code
networks:
  default:
    external:
      name: connection_api-tests
