export STORAGE_API_URL=http://connection-apache/
export STORAGE_API_TOKEN=
export STORAGE_API_LINKING_TOKEN=
export STORAGE_API_TOKEN_IN_SAME_ORGANIZATION=
export STORAGE_API_TOKEN_IN_OTHER_ORGANIZATION=
export STORAGE_API_TOKEN_USER_WITH_OTHER_EMAIL=
export STORAGE_API_TOKEN_USER_EMAIL_IN_OTHER_ORG=
export STORAGE_API_MAINTENANCE_URL=https://maintenance-testing.us-east-1.keboola.com/
